Repository algolia/places, pull requests merged in 2018-10, with the labels that each got.

#611 doc(security): Add security section in documenation
  docs/source/documentation.html.md.erb
Labels: website

#612 doc(copy-examples): fix clipboard selectors and code block style
  docs/source/javascripts/documentation-layout.js
  docs/source/stylesheets/components/_clipboard.scss
  docs/source/stylesheets/components/_code-highlight.scss
Labels: website

#613 Add Places credentials in examples
  README.md
  docs/config.rb
  docs/source/contact.html.haml
  docs/source/documentation.html.md.erb
  docs/source/examples.html.md.erb
  docs/source/javascripts/index.js
  docs/source/partials/examples/_autocomplete_dataset.html.erb
  docs/source/partials/examples/_city_search.html.erb
  docs/source/partials/examples/_complete_form.html.erb
  docs/source/partials/examples/_country_search.html.erb
  docs/source/partials/examples/_disable_styling.html.erb
  docs/source/partials/examples/_instantsearch.html.erb
  docs/source/partials/examples/_map.html.erb
  docs/source/partials/examples/_map_paris.html.erb
  docs/source/partials/examples/_simple_input.html.erb
  docs/source/partials/examples/_templates.html.erb
Labels: documentation, website

#616 doc(examples): add context and improve examples
  .ruby-version
  .travis.yml
  docs/Gemfile.lock
  docs/source/documentation.html.md.erb
  docs/source/examples.html.md.erb
  docs/source/partials/examples/_demo.html.erb
  docs/source/partials/examples/_single_country_search.html.erb
  docs/source/partials/examples/reverse-city-search/_code.html.erb
  docs/source/partials/examples/reverse-city-search/_demo.html.erb
  docs/source/partials/hero.html.haml
Labels: website

#610 feat(cta): add signup CTA on landing
  docs/source/index.html.haml
Labels: website

#617 doc(api-clients): combine rest doc and api clients doc in separate page
  docs/source/api-clients.html.md.erb
  docs/source/documentation.html.md.erb
  docs/source/index.html.haml
  docs/source/partials/navigation.html.haml
  docs/source/stylesheets/components/_documentation.scss
Labels: website

#625 doc(mobile-clients): add documentation about usage of Places in mobile clients
  docs/source/api-clients.html.md.erb
  docs/source/documentation.html.md.erb
Labels: documentation, website

#622 feat(postcodes): expose postcodes array in suggestions
  docs/source/documentation.html.md.erb
  docs/source/javascripts/index.js
  src/formatHit.js
  src/formatHit.test.js
Labels: documentation, enhancement
